baseURL: "https://unit-6.net/"
theme: "Unit-6"
languageCode: "en-us"

title: "UNIT-6"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "UNIT-6"
  description: "We specialize in providing services to automating security, building security related solutions, and security services."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    twitter: "#"

  location:
    - "Amsterdam, The Netherlands"

  contact:
    - "info@unit-6.net"

  copyright: "© 2022 Unit-6 All Rights Reserved"

  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "About Us"
      url: "/about"
      weight: 2

        #   - name: "Our team"
        #     url: "/team"
        #     weight: 3

        #    - name: "Pricing"
        #      url: "/#"
        #      weight: 4
        #
        #    - name: "Blog"
        #      url: "/blog"
        #      weight: 5

        #buttons:
        #  - name: "Book a call"
        #    url: "/#"
        #    weight: 5
        #    pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

        #   - name: "Our team"
        #     url: "/#"
        #     weight: 3

        #    - name: "Pricing"
        #      url: "/#"
        #      weight: 4
        #
        #    - name: "Blog"
        #      url: "/blog"
        #      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
